# frozen_string_literal: true

FactoryBot.define do
  factory :form do
    association :user
    name { Faker::Lorem.words(number: 3).join(' ').titleize }
    description { Faker::Lorem.paragraph }
    category { 'general' }
    status { 'draft' }
    
    # The share_token will be generated by the model's before_create callback

    trait :published do
      status { 'published' }
      published_at { Time.current }
    end

    trait :with_questions do
      after(:create) do |form|
        create_list(:form_question, 3, form: form)
      end
    end

    trait :ai_enabled do
      ai_enabled { true }
      ai_configuration do
        {
          features: ['response_analysis', 'sentiment_analysis'],
          model: 'gpt-4o-mini',
          temperature: 0.7,
          max_tokens: 500,
          confidence_threshold: 0.7
        }
      end
    end

    trait :with_payment_questions do
      after(:create) do |form|
        create(:form_question, form: form, question_type: 'text_short', title: 'Your Name', position: 1)
        create(:form_question, form: form, question_type: 'payment', title: 'Payment Information', position: 2, required: true)
        create(:form_question, form: form, question_type: 'payment', title: 'Additional Services', position: 3, required: false)
      end
    end
  end
end